modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "GPL-3.0"

[[mods]]
modId = "randomtitlerework"
version = "${version}"
displayName = "RandomTitleRework"
displayURL = "https://github.com/ThinkingStudios/RandomTitleRework"
credits = "PercyDan"
authors = "ThinkingStudio, TexTrue"
description = '''
RandomTitle unofficial 1.20.1 and above port.

Pick random sentences as window title.
'''
logoFile = "assets/randomtitlerework/icon.png"

[[mixins]]
config = "randomtitlerework.mixins.json"

[[dependencies.randomtitlerework]]
modId = "neoforge"
type = "required"
versionRange = "[20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.randomtitlerework]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.randomtitlerework]]
modId = "cloth_config"
type = "required"
versionRange = "[12,)"
ordering = "NONE"
side = "CLIENT"
